"""empty message

Revision ID: 34269ac9c7f8
Revises: 967522dbc00b
Create Date: 2025-06-29 21:21:04.272261

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '34269ac9c7f8'
down_revision = '967522dbc00b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitud',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario_lector', sa.Integer(), nullable=False),
    sa.Column('fecha_solicitud', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario_lector'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prestamo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_solicitud', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_devolucion_limite', sa.DateTime(), nullable=False),
    sa.Column('fecha_devolucion_real', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_solicitud'], ['solicitud.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('multa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_prestamo', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('fecha_generacion', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_prestamo'], ['prestamo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('autor', schema=None) as batch_op:
        batch_op.drop_column('ap_materno')

    with op.batch_alter_table('libro', schema=None) as batch_op:
        batch_op.drop_column('editorial')
        batch_op.drop_column('fecha_registro')
        batch_op.drop_column('edicion')

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('direccion')
        batch_op.drop_column('fecha_nacimiento')
        batch_op.drop_column('telefono')
        batch_op.drop_column('genero')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genero', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('telefono', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('fecha_nacimiento', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('direccion', mysql.VARCHAR(length=255), nullable=True))

    with op.batch_alter_table('libro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edicion', mysql.VARCHAR(length=150), nullable=True))
        batch_op.add_column(sa.Column('fecha_registro', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True))
        batch_op.add_column(sa.Column('editorial', mysql.VARCHAR(length=150), nullable=True))

    with op.batch_alter_table('autor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ap_materno', mysql.VARCHAR(length=100), nullable=True))

    op.drop_table('multa')
    op.drop_table('prestamo')
    op.drop_table('solicitud')
    # ### end Alembic commands ###
