"""Añadir tabla de asociacion solicitud_libro

Revision ID: 55d94712e2e1
Revises: 34269ac9c7f8
Create Date: 2025-06-29 22:54:47.429578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55d94712e2e1'
down_revision = '34269ac9c7f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitud_libro',
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('libro_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['libro_id'], ['libro.id'], ),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitud.id'], ),
    sa.PrimaryKeyConstraint('solicitud_id', 'libro_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitud_libro')
    # ### end Alembic commands ###
