"""Ampliar tamaño de columna ISBN

Revision ID: 967522dbc00b
Revises: e3c2cebb6084
Create Date: 2025-06-29 19:34:52.849235

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '967522dbc00b'
down_revision = 'e3c2cebb6084'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('libro', schema=None) as batch_op:
        batch_op.alter_column('isbn',
               existing_type=mysql.VARCHAR(length=13),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('libro', schema=None) as batch_op:
        batch_op.alter_column('isbn',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=13),
               existing_nullable=False)

    # ### end Alembic commands ###
